apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      containers:
      - name: metadata
        image: ghcr.io/bnb-chain/greenfield-storage-provider:0.0.3
        args: ["--log.std", "-c", "/config/config.toml", "-server", "metadata"]
        imagePullPolicy: Always
        env:
          # - name: Metadata_Service_DSN
          #   valueFrom:
          #     secretKeyRef:
          #       key: BLOCK_SYNCER_DSN
          #       name: gf-sp-aws-secret
          - name: BLOCK_SYNCER_DB_USER
            valueFrom:
              secretKeyRef:
                key: MDU
                name: gf-sp-aws-secret
          - name: BLOCK_SYNCER_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MDP
                name: gf-sp-aws-secret
          - name: SP_DB_USER
            valueFrom:
              secretKeyRef:
                key: MDU
                name: gf-sp-aws-secret
          - name: SP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MDP
                name: gf-sp-aws-secret
          - name: SP_DB_ADDRESS
            valueFrom:
              secretKeyRef:
                key: SP_DB_ADDRESS
                name: gf-sp-aws-secret
          - name: SP_DB_DATABASE
            value: "block_syncer"
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
        ports:
          - containerPort: 9833
            name: metadata
        volumeMounts:
        - mountPath: /config
          name: config
      imagePullSecrets:
        - name: image-pull
      volumes:
        - name: config
          configMap:
            name: config-metadata
---
apiVersion: v1
kind: Service
metadata:
  name: metadata
spec:
  ports:
  - port: 9833
    targetPort: 9833
    name: metadata
  selector:
    app: metadata
