Service = [
  "Downloader", "Challenage",
]

[DownloaderCfg]
    Address = "127.0.0.1:9233"
    [DownloaderCfg.PieceStoreConfig]
        Shards = 0
        [DownloaderCfg.PieceStoreConfig.Store]
            Storage = "s3"
            BucketURL = "https://s3.ap-northeast-1.amazonaws.com/tf-nodereal-dev-greenfield-sp-a"
            MaxRetries = 5
            TestMode = false
            AccessKey = ""
            SecretKey = ""
            #SessionToken = "SESSIONTOKEN"
            NoSignRequest = false
            TlsInsecureSkipVerify = false

[ChallengeCfg]
    Address = "127.0.0.1:9633"
    StorageProvider = "bnb-sp"
    MetaDBType = "mysql"
    #[ChallengeCfg.MetaLevelDBConfig]
        #Path = "./data/meta"
        #NameSpace = "bnb-sp"
        #Cache = 4096
        #FileHandles = 1000
        #ReadOnly = false
    [ChallengeCfg.MetaSqlDBConfig]
        User = "qebwghqo"
        Passwd = ""
        Address = "tf-20230209032748386800000001.cnvhwydws6wc.ap-northeast-1.rds.amazonaws.com:3306"
        Database = "greenfield-sp-a"
    [ChallengeCfg.PieceStoreConfig]
        Shards = 0
        [ChallengeCfg.PieceStoreConfig.Store]
            Storage = "s3"
            BucketURL = "https://s3.ap-northeast-1.amazonaws.com/tf-nodereal-dev-greenfield-sp-a"
            MaxRetries = 5
            TestMode = false
            AccessKey = ""
            SecretKey = "1vb534onOTay+tZMgyzXZPTy9AhFy+Ks366k0mCk"
            #SessionToken = "SESSIONTOKEN"
            NoSignRequest = false
            TlsInsecureSkipVerify = false
