Service = [
    "Metadata", 
]

[MetadataCfg]
    Address = "0.0.0.1:9833"
    MetaDBType = "sqldb"
    [MetadataCfg.MetaSqlDBConfig]
        User = ""
        Passwd = ""
        Address = ""
        Database = "meta_db"