Service = [
  "Uploader", "Downloader", "Challenge",
]

[UploaderCfg]
    StorageProvider = "0xf040BaaD4966842dAF83a536048a25Cf8eFF9ea0"
    Address = "0.0.0.0:9133"
    StoneHubServiceAddress = "stonehub:9333"
    [UploaderCfg.PieceStoreConfig]
        Shards = 0
        [UploaderCfg.PieceStoreConfig.Store]
            Storage = "S3"
            MaxRetries = 5
            TestMode = true
            NoSignRequest = false
            TlsInsecureSkipVerify = false
    [UploaderCfg.ChainConfig]
        ChainID = "greenfield_9000-1741"
        [[UploaderCfg.ChainConfig.NodeAddr]]
            GreenfieldAddrs = ["gnfd-grpc-plaintext.qa.bnbchain.world:9090"]
            TendermintAddrs = ["https://gnfd.qa.bnbchain.world:443"]


[DownloaderCfg]
    Address = "0.0.0.0:9233"
    [DownloaderCfg.PieceStoreConfig]
        Shards = 0
        [DownloaderCfg.PieceStoreConfig.Store]
            Storage = "S3"
            MaxRetries = 5
            TestMode = true
            NoSignRequest = false
            TlsInsecureSkipVerify = false
    [DownloaderCfg.ChainConfig]
        ChainID = "greenfield_9000-1741"
        [[DownloaderCfg.ChainConfig.NodeAddr]]
            GreenfieldAddrs = ["gnfd-grpc-plaintext.qa.bnbchain.world:9090"]
            TendermintAddrs = ["https://gnfd.qa.bnbchain.world:443"]


[ChallengeCfg]
    StorageProvider = "0xf040BaaD4966842dAF83a536048a25Cf8eFF9ea0"
    Address = "0.0.0.0:9733"
    MetaDBType = "mysql"
    [ChallengeCfg.PieceStoreConfig]
        Shards = 0
        [ChallengeCfg.PieceStoreConfig.Store]
            Storage = "s3"
            MaxRetries = 5
            TestMode = true
            NoSignRequest = false
            TlsInsecureSkipVerify = false
    [ChallengeCfg.MetaSqlDBConfig]
        Address = "greenfield-sp-qa-c-cluster.cluster-cb6vaj1ctcqk.us-east-1.rds.amazonaws.com:3306"
        Database = "meta_db"
