Service = [
  "StoneHub",
]

[StoneHubCfg]
    StorageProvider = "0xf040BaaD4966842dAF83a536048a25Cf8eFF9ea0"
    Address = "0.0.0.0:9333"
    SignerServiceAddress = "signer:9633"
    JobDBType = "mysql"
    MetaDBType = "mysql"
    [StoneHubCfg.JobSqlDBConfig]
        Address = "greenfield-sp-qa-c-cluster.cluster-cb6vaj1ctcqk.us-east-1.rds.amazonaws.com:3306"
        Database = "job_db"
    [StoneHubCfg.MetaSqlDBConfig]
        Address = "greenfield-sp-qa-c-cluster.cluster-cb6vaj1ctcqk.us-east-1.rds.amazonaws.com:3306"
        Database = "meta_db"
    [StoneHubCfg.ChainConfig]
        ChainID = "greenfield_9000-1741"
        [[StoneHubCfg.ChainConfig.NodeAddr]]
            GreenfieldAddrs = ["gnfd-grpc-plaintext.qa.bnbchain.world:9090"]
            TendermintAddrs = ["https://gnfd.qa.bnbchain.world:443"]