Service = [
  "StoneNode",
]

[StoneNodeCfg]
    StorageProvider = "bnb-sp"
    Address = "0.0.0.0:9433"
    StoneHubServiceAddress = "stonehub:9333"
    StoneJobLimit = 64
    [StoneNodeCfg.PieceStoreConfig]
        Shards = 0
        [StoneNodeCfg.PieceStoreConfig.Store]
            Storage = "s3"
            BucketURL = "https://s3.ap-northeast-1.amazonaws.com/tf-nodereal-dev-greenfield-sp-devops"
            MaxRetries = 5
            TestMode = true
            NoSignRequest = false
            TlsInsecureSkipVerify = false