apiVersion: apps/v1
kind: Deployment
metadata:
  name: stopserving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stopserving
  template:
    metadata:
      labels:
        app: stopserving
    spec:
      serviceAccountName: nodereal-default
      containers:
      - name: stopserving
        image: ghcr.io/bnb-chain/greenfield-storage-provider:0.0.3
        args: ["--log.std", "-c", "/config/config.toml", "-server", "stopserving"]
        env:
          - name: SIGNER_GC_PRIV_KEY
            valueFrom:
              secretKeyRef:
                key: SIGNER_GC_PRIV_KEY
                name: default
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - mountPath: /config
          name: config
      imagePullSecrets:
        - name: image-pull
      volumes:
        - name: config
          configMap:
            name: config
