---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - imagepullsecret.yaml
  - 00-statefulset.yaml
  - 01-deployment.yaml
  - 02-service.yaml
namespace: greenfield-sp