apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: default
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - replace-me
  selector:
    matchLabels:
      biz: storage-provider
      team: greenfield
