Service = [
  "Syncer",
]

[SyncerCfg]
    StorageProvider = "0x640314db972De50eE2d1aa28900E567DCC29566F"
    Address = "0.0.0.0:9533"
    SignerServiceAddress = "signer:9633"
    MetaDBType = "mysql"
    [SyncerCfg.PieceStoreConfig.Store]
        Storage = "s3"
        MaxRetries = 5
        TestMode = true
        NoSignRequest = false
        TlsInsecureSkipVerify = false
    [SyncerCfg.MetaSqlDBConfig]
        Address = "greenfield-sp-dev-b-cluster.cluster-cnvhwydws6wc.ap-northeast-1.rds.amazonaws.com:3306"
        Database = "meta_db"