bases:
  - ../../../base

namespace: gf-sp-a

commonLabels:
    team: greenfield
    biz: storage-provider
    cluster_id: a

configMapGenerator:
- name: config-syncer
  files:
  - configs/syncer/config.toml
- name: config-uploader-downloader-challenge
  files:
  - configs/uploader_downloader_challenge/config.toml
- name: config-gateway
  files:
  - configs/gateway/config.toml
- name: config-stonehub
  files:
  - configs/stonehub/config.toml
- name: config-stonenode
  files:
  - configs/stonenode/config.toml

patches:
- target:
    kind: Ingress
    name: gateway
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: gf-sp-a.bk.nodereal.cc
    - op: replace
      path: /spec/rules/1/host
      value: "*.gf-sp-a.bk.nodereal.cc"

patchesJson6902:
- target:
    version: v1
    kind: Secret
    name: sp-db
  patch: |-
    - op: replace
      path: /data/MDU
      value: Z3JlZW5maWVsZA==
- target:
    version: v1
    kind: Secret
    name: sp-db
  patch: |-
    - op: replace
      path: /data/MDP
      value: MDJhTVU0bWlHY2RHWlJmYg==
- target:
    version: v1
    kind: Secret
    name: sp-db
  patch: |-
    - op: replace
      path: /data/JDU
      value: Z3JlZW5maWVsZA==
- target:
    version: v1
    kind: Secret
    name: sp-db
  patch: |-
    - op: replace
      path: /data/JDP
      value: MDJhTVU0bWlHY2RHWlJmYg==
- target:
    version: v1
    kind: Secret
    name: sp-s3
  patch: |-
    - op: replace
      path: /data/AK
      value: QUtJQVZCTE1XN0FVTkRGNTNFSzc=
- target:
    version: v1
    kind: Secret
    name: sp-s3
  patch: |-
    - op: replace
      path: /data/SK
      value: ckVrSlYya0lRNDNaV3lVRnM5K0FzRHZtR0N1MDFpR0tlNjdidWNJVQ==

