Service = [
  "StoneNode",
]

[StoneNodeCfg]
    StorageProvider = "0xBb1E46c1ac6621E464931450e69e811a0D8683d2"
    Address = "0.0.0.0:9433"
    GatewayAddress = ["gateway.gf-sp-a.svc.cluster.local:9033", "gateway.gf-sp-b.svc.cluster.local:9033", "gateway.gf-sp-c.svc.cluster.local:9033", "gateway.gf-sp-d.svc.cluster.local:9033", "gateway.gf-sp-f.svc.cluster.local:9033", "gateway.gf-sp-g.svc.cluster.local:9033"]
    StoneHubServiceAddress = "stonehub:9333"
    StoneJobLimit = 64
    [StoneNodeCfg.PieceStoreConfig]
        Shards = 0
        [StoneNodeCfg.PieceStoreConfig.Store]
            Storage = "s3"
            BucketURL = "https://s3.ap-northeast-1.amazonaws.com/tf-nodereal-dev-greenfield-sp-e"
            MaxRetries = 5
            TestMode = true
            NoSignRequest = false
            TlsInsecureSkipVerify = false