apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2p
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2p
  template:
    metadata:
      labels:
        app: p2p
    spec:
      serviceAccountName: nodereal-default
      containers:
      - name: p2p
        image: ghcr.io/bnb-chain/greenfield-storage-provider:0.0.4-p2p
        args: ["--log.std", "-c", "/config/config.toml", "-server", "p2p"]
        imagePullPolicy: Always
        env:
          - name: P2P_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: P2P_PRIVATE_KEY
                name: default
          - name: SP_DB_USER
            valueFrom:
              secretKeyRef:
                key: SP_DB_USER
                name: default
          - name: SP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: SP_DB_PASSWORD
                name: default
          - name: SP_DB_ADDRESS
            valueFrom:
              secretKeyRef:
                key: SP_DB_ADDRESS
                name: default
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 8Gi
        ports:
          - containerPort: 9833
            name: p2p
          - containerPort: 9933
            name: p2p-external
        volumeMounts:
        - mountPath: /config
          name: config
        - name: data
          mountPath: /app/data
      imagePullSecrets:
        - name: image-pull
      volumes:
        - name: config
          configMap:
            name: config
        - name: data
          persistentVolumeClaim:
            claimName: p2p-data
---
apiVersion: v1
kind: Service
metadata:
  name: p2p
spec:
  ports:
  - port: 9833
    targetPort: 9833
    name: p2p
  selector:
    app: p2p
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p2p-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc # Patch this accordingly or remove it to use default SC in the cluster.
  resources:
    requests:
      storage: 10Gi
---
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-subnets: null
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  name: p2p-external
spec:
  type: LoadBalancer
  ports:
  - port: 9933
    targetPort: 9933
    name: p2p-external
  selector:
    app: p2p

