apiVersion: v1
kind: ServiceAccount
metadata:
  name: sp-default
  annotations:
    eks.amazonaws.com/role-arn: replace-me
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: replace-me
      auth:
        jwt:
          serviceAccountRef:
            name: sp-default
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: default
  target:
    name: default
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: replace-me

