apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: default
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - replace-me
  selector:
    matchLabels:
      biz: storage-provider
      team: greenfield
---
# the following added to sync with argocd when the above ServiceMonitor resource generate VMServiceScrape
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: default
spec:
  endpoints:
    - attach_metadata: {}
      interval: 30s
      path: /metrics
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - replace-me
  selector:
    matchLabels:
      biz: storage-provider
      team: greenfield

