Service = [
  "StoneHub",
]

[StoneHubCfg]
    StorageProvider = "0xBb1E46c1ac6621E464931450e69e811a0D8683d2"
    Address = "0.0.0.0:9333"
    SignerServiceAddress = "signer:9633"
    JobDBType = "mysql"
    MetaDBType = "mysql"
    [StoneHubCfg.JobSqlDBConfig]
        Address = "greenfield-sp-dev-e-cluster.cluster-cnvhwydws6wc.ap-northeast-1.rds.amazonaws.com:3306"
        Database = "job_db"
    [StoneHubCfg.MetaSqlDBConfig]
        Address = "greenfield-sp-dev-e-cluster.cluster-cnvhwydws6wc.ap-northeast-1.rds.amazonaws.com:3306"
        Database = "meta_db"
    [StoneHubCfg.ChainConfig]
        ChainID = "greenfield_9000-1741"
        [[StoneHubCfg.ChainConfig.NodeAddr]]
            GreenfieldAddrs = ["gnfd-grpc-plaintext-dev.bnbchain.world:9090"]
            TendermintAddrs = ["https://gnfd-dev.bnbchain.world:443"]