Service = [
  "StoneNode",
]

[StoneNodeCfg]
    StorageProvider = "bnb-sp"
    Address = "127.0.0.1:9433"
    StoneHubServiceAddress = "127.0.0.1:9333"
    SyncerServiceAddress = "127.0.0.1:9533"
    StoneJobLimit = 64
    [StoneNodeCfg.PieceConfig]
        Shards = 0
        [StoneNodeCfg.PieceConfig.Store]
            Storage = "s3"
            BucketURL = "https://s3.ap-northeast-1.amazonaws.com/tf-nodereal-dev-greenfield-sp-a"
            MaxRetries = 5
            TestMode = false
            AccessKey = "AKIAVBLMW7AUJY4FEPQR"
            SecretKey = "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"
            #SessionToken = "SESSIONTOKEN"
            NoSignRequest = false
            TlsInsecureSkipVerify = false
