Service = [
  "Gateway",
]

[GatewayCfg]
    StorageProvider = "0x640314db972De50eE2d1aa28900E567DCC29566F"
    Address = "0.0.0.0:9033"
    Domain = "gf-sp-b-bk.dev.nodereal.cc"
    UploaderServiceAddress = "uploader:9133"
    DownloaderServiceAddress = "downloader:9233"
    SyncerServiceAddress = "syncer:9533"
    SignerServiceAddress = "signer:9633"
    ChallengeServiceAddress = "challenge:9733"
    [GatewayCfg.ChainConfig]
        ChainID = "greenfield_9000-1741"
        [[GatewayCfg.ChainConfig.NodeAddr]]
            GreenfieldAddrs = ["gnfd-grpc-plaintext-dev.bnbchain.world:9090"]
            TendermintAddrs = ["https://gnfd-dev.bnbchain.world:443"]