Service = [
  "Downloader", "Challenage",
]

[DownloaderCfg]
    Address = "127.0.0.1:9233"
    [DownloaderCfg.PieceStoreConfig]
        Shards = 0
        [DownloaderCfg.PieceStoreConfig.Store]
            Storage = "s3"
            BucketURL = "./data/primary_payload_data"
            MaxRetries = 5
            TestMode = true
            AccessKey = "ACCESSKEY"
            SecretKey = "SECRETKEY"
            SessionToken = "SESSIONTOKEN"
            NoSignRequest = false
            TlsInsecureSkipVerify = false

[ChallengeCfg]
    Address = "127.0.0.1:9633"
    StorageProvider = "bnb-sp"
    MetaDBType = "mysql"
    [ChallengeCfg.MetaLevelDBConfig]
        Path = "./data/meta"
        NameSpace = "bnb-sp"
        Cache = 4096
        FileHandles = 1000
        ReadOnly = false
    [ChallengeCfg.MetaSqlDBConfig]
        User = "root"
        Passwd = "test_pwd"
        Address = "127.0.0.1:3306"
        Database = "meta_db"
    [ChallengeCfg.PieceStoreConfig]
        Shards = 0
        [ChallengeCfg.PieceStoreConfig.Store]
            Storage = "s3"
            BucketURL = "./data/primary_payload_data"
            MaxRetries = 5
            TestMode = true
            AccessKey = "ACCESSKEY"
            SecretKey = "SECRETKEY"
            SessionToken = "SESSIONTOKEN"
            NoSignRequest = false
            TlsInsecureSkipVerify = false
