Service = [
  "Syncer",
]

[SyncerCfg]
    StorageProvider = "0x20Bb76D063a6d2B18B6DaBb2aC985234a4B9eDe0"
    Address = "0.0.0.0:9533"
    SignerServiceAddress = "signer:9633"
    MetaDBType = "mysql"
    [SyncerCfg.PieceStoreConfig.Store]
        Storage = "s3"
        MaxRetries = 5
        TestMode = true
        NoSignRequest = false
        TlsInsecureSkipVerify = false
    [SyncerCfg.MetaSqlDBConfig]
        Address = "greenfield-sp-qa-f-cluster.cluster-cb6vaj1ctcqk.us-east-1.rds.amazonaws.com:3306"
        Database = "meta_db"