Service = [
  "Syncer",
]

[SyncerCfg]
    StorageProvider = "bnb-sp"
    Address = "127.0.0.1:9533"
    MetaDBType = "mysql"
    [SyncerCfg.PieceConfig.Store]
        Storage = "s3"
        BucketURL = "https://s3.ap-northeast-1.amazonaws.com/tf-nodereal-dev-greenfield-sp-a"
        MaxRetries = 5
        TestMode = true
        NoSignRequest = false
        TlsInsecureSkipVerify = false
    [SyncerCfg.MetaSqlDBConfig]
        Address = "tf-20230210045544154100000001.cnvhwydws6wc.ap-northeast-1.rds.amazonaws.com:3306"
        Database = "meta_db"
