Service = [
  "Uploader",
]
      
[UploaderCfg]
    StorageProvider = "bnb-sp"
    Address = "127.0.0.1:9133"
    StoneHubServiceAddress = "127.0.0.1:9333"
    MetaDBType = "mysql"
    [UploaderCfg.PieceStoreConfig]
        Shards = 0
        [UploaderCfg.PieceStoreConfig.Store]
            Storage = "s3"
            BucketURL = "https://s3.ap-northeast-1.amazonaws.com/tf-nodereal-dev-greenfield-sp-a"
            MaxRetries = 5
            TestMode = false
            AccessKey = ""
            SecretKey = "1vb534onOTay+tZMgyzXZPTy9AhFy+Ks366k0mCk"
            #SessionToken = "SESSIONTOKEN"
            NoSignRequest = false
            TlsInsecureSkipVerify = false
    #[UploaderCfg.MetaLevelDBConfig]
        #Path = "./data/meta"
        #NameSpace = "bnb-sp"
        #Cache = 4096
        #FileHandles = 1000
        #ReadOnly = false
    [UploaderCfg.MetaSqlDBConfig]
        User = "qebwghqo"
        Passwd = ""
        Address = "tf-20230209032748386800000001.cnvhwydws6wc.ap-northeast-1.rds.amazonaws.com:3306"
        Database = "greenfield-sp-a"
