Service = [
  "StoneHub",
]

[StoneHubCfg]
StorageProvider = "bnb-sp"
Address = "127.0.0.1:9333"
JobDBType = "mysql"
MetaDBType = "mysql"
[StoneHubCfg.JobSqlDBConfig]
    Database = "job_db"
[StoneHubCfg.MetaSqlDBConfig]
    Address = "127.0.0.1:3306"
    Database = "meta_db"