Service = [
    "Metadata", 
]

[MetadataCfg]
    Address = "0.0.0.0:9833"
    MetaDBType = "mysql"
    [MetadataCfg.MetaSqlDBConfig]
        User = ""
        Passwd = ""
        Address = "greenfield-sp-dev-g-cluster.cluster-cnvhwydws6wc.ap-northeast-1.rds.amazonaws.com:3306"
        Database = "block_syncer"