Service = [
    "Metadata", 
]

[MetadataCfg]
    Address = "0.0.0.0:9833"
    MetaDBType = "sqldb"
    [MetadataCfg.MetaSqlDBConfig]
        User = "root"
        Passwd = "1234"
        Address = "127.0.0.1:3306"
        Database = "meta_db"