Service = [
  "StoneNode",
]

[StoneNodeCfg]
    StorageProvider = "0xf040BaaD4966842dAF83a536048a25Cf8eFF9ea0"
    Address = "0.0.0.0:9433"
    GatewayAddress = ["gf-sp-a.bk.nodereal.cc", "gf-sp-b.bk.nodereal.cc", "gf-sp-d.bk.nodereal.cc", "gf-sp-e.bk.nodereal.cc", "gf-sp-f.bk.nodereal.cc", "gf-sp-g.bk.nodereal.cc"]
    StoneHubServiceAddress = "stonehub:9333"
    StoneJobLimit = 64
    [StoneNodeCfg.PieceStoreConfig]
        Shards = 0
        [StoneNodeCfg.PieceStoreConfig.Store]
            Storage = "s3"
            BucketURL = "https://s3.us-east-1.amazonaws.com/tf-nodereal-qa-greenfield-sp-c"
            MaxRetries = 5
            TestMode = true
            NoSignRequest = false
            TlsInsecureSkipVerify = false