Service = [
  "Gateway",
]

[GatewayCfg]
    Address = "0.0.0.0:9033"
    Domain = "gf-sp-g.bk.nodereal.cc"
    UploaderServiceAddress = "uploader:9133"
    DownloaderServiceAddress = "downloader:9233"
