Service = [
  "Gateway",
]

[GatewayCfg]
    StorageProvider = "0x70d1983A9A76C8d5d80c4cC13A801dc570890819"
    Address = "0.0.0.0:9033"
    Domain = "gf-sp-g.bk.nodereal.cc"
    UploaderServiceAddress = "uploader:9133"
    DownloaderServiceAddress = "downloader:9233"
    SyncerServiceAddress = "syncer:9533"
    SignerServiceAddress = "signer:9633"
    ChallengeServiceAddress = "challenge:9733"
    [GatewayCfg.ChainConfig]
        ChainID = "greenfield_9000-1741"
        [[GatewayCfg.ChainConfig.NodeAddr]]
            GreenfieldAddrs = ["gnfd-grpc-plaintext.qa.bnbchain.world:9090"]
            TendermintAddrs = ["https://gnfd.qa.bnbchain.world:443"]