bases:
  - ../../../base

namespace: gf-sp-devops

commonLabels:
    team: greenfield
    biz: storage-provider

configMapGenerator:
- name: config-syncer
  files:
  - configs/syncer/config.toml
- name: config-uploader-downloader-challenge
  files:
  - configs/uploader_downloader_challenge/config.toml
- name: config-gateway
  files:
  - configs/gateway/config.toml
- name: config-stonehub
  files:
  - configs/stonehub/config.toml
- name: config-stonenode
  files:
  - configs/stonenode/config.toml
- name: config-metadata
  files:
  - configs/metadata/config.toml
- name: config-signer
  files:
  - configs/signer/config.toml

patches:
- target:
    kind: Ingress
    name: gateway
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: gf-sp-devops-bk.dev.nodereal.cc
    - op: replace
      path: /spec/rules/1/host
      value: "*.gf-sp-devops-bk.dev.nodereal.cc"
- target:
    kind: ServiceAccount
    name: patch-me-sa
  patch: |-
    - op: replace
      path: /metadata/name
      value: gf-sp-devops-credential-sa
    - op: replace
      path: /metadata/annotations/eks.amazonaws.com~1role-arn
      value: arn:aws:iam::346509735976:role/tf-nodereal-dev-greenfield-sp-devops-role
- target:
    kind: SecretStore
    name: gf-sp-secret-store
  patch: |-
    - op: replace
      path: /spec/provider/aws/region
      value: ap-northeast-1
    - op: replace
      path: /spec/provider/aws/auth/jwt/serviceAccountRef/name
      value: gf-sp-devops-credential-sa
- target:
    kind: ExternalSecret
    name: gf-sp-es
  patch: |-
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: /dev/greenfield/sp/RDS_USER
    - op: replace
      path: /spec/data/1/remoteRef/key
      value: /dev/greenfield/sp/RDS_PASSWORD
    - op: replace
      path: /spec/data/2/remoteRef/key
      value: /dev/greenfield/sp/RDS_USER
    - op: replace
      path: /spec/data/3/remoteRef/key
      value: /dev/greenfield/sp/RDS_PASSWORD
    - op: replace
      path: /spec/data/4/remoteRef/key
      value: /dev/greenfield/gf-sp-devops/AWS_ACCESS_KEY
    - op: replace
      path: /spec/data/5/remoteRef/key
      value: /dev/greenfield/gf-sp-devops/AWS_SECRET_KEY
    - op: replace
      path: /spec/data/6/remoteRef/key
      value: /dev/greenfield/gf-sp-devops/AWS_BUCKET_URL
    - op: replace
      path: /spec/data/7/remoteRef/key
      value: /dev/greenfield/gf-sp-a/BLOCK_SYNCER_DSN
# the following patch for test, can be update related yaml when release
# - target:
#     kind: StatefulSet
#     name: stonehub
#   patch: |-
#     - op: replace
#       path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/2/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/3/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
# - target:
#     kind: Deployment
#     name: stonenode
#   patch: |-
#     - op: replace
#       path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/3/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
# - target:
#     kind: Deployment
#     name: syncer
#   patch: |-
#     - op: replace
#       path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/3/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/4/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/5/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/6/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/7/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
# - target:
#     kind: Deployment
#     name: uploader-downloader-challenge
#   patch: |-
#     - op: replace
#       path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/1/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/3/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/4/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret
#     - op: replace
#       path: /spec/template/spec/containers/0/env/5/valueFrom/secretKeyRef/name
#       value: gf-sp-aws-secret

# patchesJson6902:
# - target:
#     version: v1
#     kind: Secret
#     name: sp-db
#   patch: |-
#     - op: replace
#       path: /data/MDU
#       value: Z3JlZW5maWVsZA==
# - target:
#     version: v1
#     kind: Secret
#     name: sp-db
#   patch: |-
#     - op: replace
#       path: /data/MDP
#       value: MDJhTVU0bWlHY2RHWlJmYg==
# - target:
#     version: v1
#     kind: Secret
#     name: sp-db
#   patch: |-
#     - op: replace
#       path: /data/JDU
#       value: Z3JlZW5maWVsZA==
# - target:
#     version: v1
#     kind: Secret
#     name: sp-db
#   patch: |-
#     - op: replace
#       path: /data/JDP
#       value: MDJhTVU0bWlHY2RHWlJmYg==
# - target:
#     version: v1
#     kind: Secret
#     name: sp-s3
#   patch: |-
#     - op: replace
#       path: /data/AK
#       value: QUtJQVZCTE1XN0FVTVRLVExQR1o=
# - target:
#     version: v1
#     kind: Secret
#     name: sp-s3
#   patch: |-
#     - op: replace
#       path: /data/SK
#       value: QUtwM3R0SzRKVmRxWjFReTd5K1JKdUFLQ29OQVRpNHpxdzZoZDkrQQ==
# - target:
#     version: v1
#     kind: Secret
#     name: sp-s3
#   patch: |-
#     - op: replace
#       path: /data/BUCKET_URL
#       value: aHR0cHM6Ly9zMy5hcC1ub3J0aGVhc3QtMS5hbWF6b25hd3MuY29tL3RmLW5vZGVyZWFsLWRldi1ncmVlbmZpZWxkLXNwLWRldm9wcw==
