{
 "title": "Storage Provider - OpenSource",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "site",
    "label": "site",
    "query": {
     "query": "label_values(prometheus_replica)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{prometheus_replica=\"$site\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "POD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{container!=\"\",namespace=~\"$namespace\", prometheus_replica=\"$site\"})) by (namespace,pod,container) / (sum(kube_pod_container_resource_limits_cpu_cores{container!=\"\",namespace=~\"$namespace\", prometheus_replica=\"$site\"}) by (namespace,pod,container)))",
       "legendFormat": "{{namespace}}/{{pod}}"
      }
     ]
    },
    {
     "title": "memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{container!=\"\", container!=\"POD\", prometheus_replica=~\"$site\", namespace=~\"$namespace\"}/container_spec_memory_limit_bytes{container!=\"\",container!=\"POD\", prometheus_replica=~\"$site\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Network In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\", prometheus_replica=\"$site\", pod!=\"\"}[$__rate_interval]))by (prometheus_replica, pod, namespace)",
       "legendFormat": "{{namespace}}/Out/{{pod}}"
      },
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\", prometheus_replica=\"$site\", pod!=\"\"}[$__rate_interval]))by (prometheus_replica, pod, namespace)",
       "legendFormat": "{{namespace}}/In/{{pod}}"
      }
     ]
    },
    {
     "title": "disk In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", prometheus_replica=\"$site\", pod!=\"\"}[5m])) by (pod,device)",
       "legendFormat": "{{pod}}/{{device}}/write"
      },
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", prometheus_replica=\"$site\", pod!=\"\"}[5m])) by (pod,device)",
       "legendFormat": "{{pod}}/{{device}}/read"
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway - HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP - P90 request latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum by (job, le, method, handler_name, namespace) (rate(http_request_duration_seconds_bucket{prometheus_replica=\"$site\", namespace=~\"$namespace\"}[1m])))",
       "legendFormat": "{{namespace}}/{{job}}/{{method}}/{{handler_name}}"
      }
     ]
    },
    {
     "title": "HTTP - peak total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "http_server_received_total_requests{prometheus_replica=\"$site\", namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "HTTP - QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_received_total_requests{prometheus_replica=\"$site\", namespace=~\"$namespace\"}[1m]))by(job,method,handler_name,namespace)",
       "legendFormat": "{{namespace}}/{{job}}/{{method}}/{{handler_name}}"
      }
     ]
    },
    {
     "title": "HTTP - Received Total Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(http_server_received_total_requests{prometheus_replica=\"$site\",namespace=~\"$namespace\"})by(namespace,method,handler_name)",
       "legendFormat": "{{namespace}}/{{method}}/{{handler_name}}"
      }
     ]
    },
    {
     "title": "HTTP - Average duration per API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_sum{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(job, method, handler_name, namespace)/sum(rate(http_request_duration_seconds_count{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(job, method, handler_name, namespace)",
       "legendFormat": "{{namespace}}/{{job}}/{{method}}/{{handler_name}}"
      }
     ]
    },
    {
     "title": "HTTP - Total QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_received_total_requests{prometheus_replica=\"$site\", namespace=~\"$namespace\"}[1m]))by(job,namespace,code)",
       "legendFormat": "{{namespace}}/{{job}}/{{method}}/{{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GRPC Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GRPC - P90 request latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(grpc_server_handling_seconds_bucket{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m])) by (le, grpc_service, grpc_method, namespace))",
       "legendFormat": "{{namespace}}/{{grpc_method}}/{{grpc_service}}"
      }
     ]
    },
    {
     "title": "GRPC - QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handling_seconds_count{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(grpc_method,grpc_service,namespace)",
       "legendFormat": "{{namespace}}/{{grpc_method}}{{grpc_service}}"
      }
     ]
    },
    {
     "title": "GRPC - Average duration per API ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handling_seconds_sum{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(grpc_method, grpc_service, namespace)/sum(rate(grpc_server_handling_seconds_count{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(grpc_method, grpc_service, namespace)",
       "legendFormat": "{{namespace}}/{{grpc_method}}/{{grpc_service}}"
      }
     ]
    },
    {
     "title": "GRPC - Total Request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(grpc_server_handled_total{prometheus_replica=\"$site\", namespace=~\"$namespace\"})by(namespace,grpc_method,grpc_service)",
       "legendFormat": "{{namespace}}/{{grpc_method}}/{{grpc_service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GRPC Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GRPC - P90 request latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(grpc_client_handling_seconds_bucket{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m])) by (le, grpc_service, grpc_method,namespace))",
       "legendFormat": "{{namespace}}/{{grpc_method}}/{{grpc_service}}"
      }
     ]
    },
    {
     "title": "GRPC - QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handling_seconds_count{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(grpc_method,grpc_service,namespace)",
       "legendFormat": "{{namespace}}/{{grpc_method}}{{grpc_service}}"
      }
     ]
    },
    {
     "title": "HTTP - Average duration per API ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handling_seconds_sum{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(grpc_method, grpc_service,namespace)/sum(rate(grpc_client_handling_seconds_count{prometheus_replica=\"$site\",namespace=~\"$namespace\"}[1m]))by(grpc_method, grpc_service,namespace)",
       "legendFormat": "{{namespace}}/{{grpc_method}}/{{grpc_service}}"
      }
     ]
    },
    {
     "title": "GRPC - Total Request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(grpc_client_handled_total{prometheus_replica=\"$site\",namespace=~\"$namespace\"})by(namespace,grpc_method,grpc_service)",
       "legendFormat": "{{namespace}}/{{grpc_method}}/{{grpc_service}}"
      }
     ]
    }
   ]
  }
 ]
}