Service = [
  "Gateway",
]

[GatewayCfg]
    StorageProvider = "bnb-sp"
    Address = "0.0.0.0:9033"
    Domain = "gf-sp-devops-bk.dev.nodereal.cc"
    UploaderServiceAddress = "uploader:9133"
    DownloaderServiceAddress = "downloader:9233"
    SyncerServiceAddress = "syncer:9533"
    SignerServiceAddress = "signer:9633"
    ChallengeServiceAddress = "challenge:9733"
    [GatewayCfg.ChainConfig]
        ChainID = "greenfield_9000-1741"
        [[GatewayCfg.ChainConfig.NodeAddr]]
            GreenfieldAddrs = ["nfd-grpc-plaintext-dev.bnbchain.world:9090"]
            TendermintAddrs = ["https://gnfd.qa.bnbchain.world:443"]