Service = [
  "Syncer",
]

[SyncerCfg]
    StorageProvider = "0x5f35A1c1366A1c9e17B71C772C4D73fb688463c7"
    Address = "0.0.0.0:9533"
    SignerServiceAddress = "signer:9633"
    MetaDBType = "mysql"
    [SyncerCfg.PieceStoreConfig.Store]
        Storage = "s3"
        MaxRetries = 5
        TestMode = true
        NoSignRequest = false
        TlsInsecureSkipVerify = false
    [SyncerCfg.MetaSqlDBConfig]
        Address = "greenfield-sp-dev-d-cluster.cluster-cnvhwydws6wc.ap-northeast-1.rds.amazonaws.com:3306"
        Database = "meta_db"