Service = [
  "StoneNode",
]

[StoneNodeCfg]
    StorageProvider = "0xca807A58caF20B6a4E3eDa3531788179E5bc816b"
    Address = "0.0.0.0:9433"
    GatewayAddress = ["gateway.gf-sp-a.svc.cluster.local:9033", "gateway.gf-sp-b.svc.cluster.local:9033", "gateway.gf-sp-c.svc.cluster.local:9033", "gateway.gf-sp-e.svc.cluster.local:9033", "gateway.gf-sp-f.svc.cluster.local:9033", "gateway.gf-sp-g.svc.cluster.local:9033"]
    StoneHubServiceAddress = "stonehub:9333"
    StoneJobLimit = 64
    [StoneNodeCfg.PieceStoreConfig]
        Shards = 0
        [StoneNodeCfg.PieceStoreConfig.Store]
            Storage = "s3"
            BucketURL = "https://s3.us-east-1.amazonaws.com/tf-nodereal-qa-greenfield-sp-d"
            MaxRetries = 5
            TestMode = true
            NoSignRequest = false
            TlsInsecureSkipVerify = false