bases:
  - ../../../base

namespace: gf-sp-d

commonLabels:
    team: greenfield
    biz: storage-provider

configMapGenerator:
- name: config-syncer
  files:
  - configs/syncer/config.toml
- name: config-uploader-downloader-challenge
  files:
  - configs/uploader_downloader_challenge/config.toml
- name: config-gateway
  files:
  - configs/gateway/config.toml
- name: config-stonehub
  files:
  - configs/stonehub/config.toml
- name: config-stonenode
  files:
  - configs/stonenode/config.toml

patchesJson6902:
- target:
    version: v1
    kind: Secret
    name: sp-db
  patch: |-
    - op: replace
      path: /data/MDU
      value: cHl1aHFqc3c=
- target:
    version: v1
    kind: Secret
    name: sp-db
  patch: |-
    - op: replace
      path: /data/MDP
      value: bVRxbWNFUllFTm1fUkVJSA==
- target:
    version: v1
    kind: Secret
    name: sp-db
  patch: |-
    - op: replace
      path: /data/JDU
      value: cHl1aHFqc3c=
- target:
    version: v1
    kind: Secret
    name: sp-db
  patch: |-
    - op: replace
      path: /data/JDP
      value: bVRxbWNFUllFTm1fUkVJSA==
- target:
    version: v1
    kind: Secret
    name: sp-s3
  patch: |-
    - op: replace
      path: /data/AK
      value: QUtJQVZCTE1XN0FVTklYTk5CSVI=
- target:
    version: v1
    kind: Secret
    name: sp-s3
  patch: |-
    - op: replace
      path: /data/SK
      value: bko2TGNRclRqQU5QNzJvSVc3djhzUGVpUlJOMVFjZWNjL1BZMVk0Wg==

