Service = [
  "StoneNode",
]

[StoneNodeCfg]
    StorageProvider = "bnb-sp"
    Address = "0.0.0.0:9433"
    StoneHubServiceAddress = "stonehub:9333"
    SyncerServiceAddress = ["syncer.gf-sp-a.svc.cluster.local:9533","syncer.gf-sp-b.svc.cluster.local:9533",
                            "syncer.gf-sp-c.svc.cluster.local:9533","syncer.gf-sp-d.svc.cluster.local:9533",
                            "syncer.gf-sp-e.svc.cluster.local:9533","syncer.gf-sp-f.svc.cluster.local:9533",]
    StoneJobLimit = 64
    [StoneNodeCfg.PieceConfig]
        Shards = 0
        [StoneNodeCfg.PieceConfig.Store]
            Storage = "s3"
            BucketURL = "https://s3.ap-northeast-1.amazonaws.com/tf-nodereal-dev-greenfield-sp-g"
            MaxRetries = 5
            TestMode = true
            NoSignRequest = false
            TlsInsecureSkipVerify = false
