Service = [
  "Gateway",
]

[GatewayCfg]
    StorageProvider = "0x2e7607cCf74Ee3B4241703c5b12305333871D831"
    Address = "0.0.0.0:9033"
    Domain = "gf-sp-g-bk.dev.nodereal.cc"
    MetadataServiceAddress = "metadata:9833"
    UploaderServiceAddress = "uploader:9133"
    DownloaderServiceAddress = "downloader:9233"
    SyncerServiceAddress = "syncer:9533"
    SignerServiceAddress = "signer:9633"
    ChallengeServiceAddress = "challenge:9733"
    MetadataServiceAddress = "metadata:9833"
    [GatewayCfg.ChainConfig]
        ChainID = "greenfield_9000-1741"
        [[GatewayCfg.ChainConfig.NodeAddr]]
            GreenfieldAddrs = ["gnfd-grpc-plaintext-dev.bnbchain.world:9090"]
            TendermintAddrs = ["https://gnfd-dev.bnbchain.world:443"]