Service = [
  "Gateway",
]

[GatewayCfg]
    StorageProvider = "xxx"
    Address = "0.0.0.0:9033"
    Domain = "gf-sp-g-bk.dev.nodereal.cc"
    MetadataServiceAddress = "metadata:9833"
    UploaderServiceAddress = "uploader:9133"
    DownloaderServiceAddress = "downloader:9233"
    SyncerServiceAddress = "syncer:9533"
    SignerServiceAddress = "singer:9633"
    ChallengeServiceAddress = "challenge:9733"
    [GatewayCfg.ChainConfig]
        ChainID = "greenfield_9000-1741"
        [[GatewayCfg.ChainConfig.NodeAddr]]
            GreenfieldAddrs = ["localhost:9090"]
            TendermintAddrs = ["http://0.0.0.0:26750"]