Service = [
  "Syncer",
]

[SyncerCfg]
    StorageProvider = "bnb-sp"
    Address = "0.0.0.0:9533"
    MetaDBType = "mysql"
    [SyncerCfg.PieceConfig.Store]
        Storage = "s3"
        BucketURL = "https://s3.us-east-1.amazonaws.com/tf-nodereal-qa-greenfield-sp-a"
        MaxRetries = 5
        TestMode = true
        NoSignRequest = false
        TlsInsecureSkipVerify = false
    [SyncerCfg.MetaSqlDBConfig]
        Address = "greenfield-sp-qa-a-cluster.cluster-cb6vaj1ctcqk.us-east-1.rds.amazonaws.com:3306"
        Database = "meta_db"
