---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gf-sp-role
  namespace: patch-me-ns #need to replace to gf-sp-devops
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create","list","watch"]
  - apiGroups: [""]
    resources: ["pods","services","endpoints"]
    verbs: ["get","watch","list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gf-sp-rolebinding
  namespace: patch-me-ns #need to replace to gf-sp-devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gf-sp-role
subjects:
  - kind: ServiceAccount
    name: patch-me-sa #need to replace to gf-sp-devops-credential-sa
    namespace: patch-me-sa-ns #need to replace to gf-sp-devops
