apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: receiver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: receiver
    spec:
      serviceAccountName: sp-default
      containers:
      - name: receiver
        image: ghcr.io/bnb-chain/greenfield-storage-provider:0.0.3
        args: ["--log.std", "-c", "/config/config.toml", "-server", "receiver"]
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 2Gi
        ports:
          - containerPort: 9333
            name: receiver
          - containerPort: 24367
            name: metrics
          - containerPort: 24368
            name: pprof
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
        - name: config
          configMap:
            name: config
---
apiVersion: v1
kind: Service
metadata:
  name: receiver
spec:
  ports:
  - port: 9333
    targetPort: 9333
    name: receiver
  - port: 24367
    targetPort: 24367
    name: metrics
  - port: 24368
    targetPort: 24368
    name: pprof
  selector:
    app: receiver
