apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: receiver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: receiver
    spec:
      serviceAccountName: nodereal-default
      containers:
      - name: receiver
        image: ghcr.io/bnb-chain/greenfield-storage-provider:0.0.3
        imagePullPolicy: Always
        args: ["--log.std", "-c", "/config/config.toml", "-server", "receiver"]
        env:
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_ACCESS_KEY
                name: default
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_SECRET_KEY
                name: default
          - name: AWS_SESSION_TOKEN
            value: ""
          - name: SP_DB_USER
            valueFrom:
              secretKeyRef:
                key: SP_DB_USER
                name: default
          - name: SP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: SP_DB_PASSWORD
                name: default
          - name: SP_DB_ADDRESS
            valueFrom:
              secretKeyRef:
                key: SP_DB_ADDRESS
                name: default
          - name: BUCKET_URL
            valueFrom:
              secretKeyRef:
                key: BUCKET_URL
                name: default
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "4"
            memory: 8Gi
        ports:
          - containerPort: 9533
            name: receiver
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      imagePullSecrets:
        - name: image-pull
      volumes:
        - name: config
          configMap:
            name: config
---
apiVersion: v1
kind: Service
metadata:
  name: receiver
spec:
  ports:
  - port: 9533
    targetPort: 9533
    name: receiver
  selector:
    app: receiver
